apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: twitter-sentiment-client-d
  labels:
    app: twitter-sentiment-client
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: twitter-sentiment-client
        tier: backend
    spec:
      containers:
      - name: twitter-sentiment-client-app
        image: gcr.io/twitter-sentiment-app/twitter-sentiment-client
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
